// <auto-generated />
using FreshMarqueSnailsERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FreshMarqueSnailsERP.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180425145412_InitialMigration-Models")]
    partial class InitialMigrationModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FreshMarqueSnailsERP.Models.DispatchRider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company")
                        .IsRequired();

                    b.Property<int>("Contact");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Supervisor")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("DispatchRiders");
                });

            modelBuilder.Entity("FreshMarqueSnailsERP.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<string>("Contact")
                        .IsRequired();

                    b.Property<decimal>("Cost");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("DeliveryDate");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("JumboSize");

                    b.Property<int>("JumboSizeQuantity");

                    b.Property<int>("LargeSize");

                    b.Property<int>("LargeSizeQuantity");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("MediumSize");

                    b.Property<int>("MediumSizeQuantity");

                    b.Property<DateTime>("OrderDate");

                    b.Property<int>("PaymentMethod");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FreshMarqueSnailsERP.Models.Retailer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Contact");

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Retailers");
                });

            modelBuilder.Entity("FreshMarqueSnailsERP.Models.RetailSupply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<decimal>("Cost");

                    b.Property<int>("JumboSize");

                    b.Property<int>("JumboSizeQuantity");

                    b.Property<int>("LargeSize");

                    b.Property<int>("LargeSizeQuantity");

                    b.Property<int>("MediumSize");

                    b.Property<int>("MediumSizeQuantity");

                    b.Property<DateTime>("SupplyDate");

                    b.HasKey("Id");

                    b.ToTable("RetailSupplies");
                });

            modelBuilder.Entity("FreshMarqueSnailsERP.Models.SnailPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<decimal>("Cost");

                    b.Property<DateTime>("PurchaseDate");

                    b.HasKey("Id");

                    b.ToTable("SnailPurchases");
                });

            modelBuilder.Entity("FreshMarqueSnailsERP.Models.SnailSpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<decimal>("Height");

                    b.Property<string>("Size")
                        .IsRequired();

                    b.Property<decimal>("Width");

                    b.HasKey("Id");

                    b.ToTable("SnailSpecifications");
                });

            modelBuilder.Entity("FreshMarqueSnailsERP.Models.SnailType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("SnailTypes");
                });

            modelBuilder.Entity("FreshMarqueSnailsERP.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Contact");

                    b.Property<DateTime>("LastSupply");

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Reliability")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
